### ISSUE TITLE
How to modify the scroll Bar in DataTable ?

### ISSUE THREAD

**Issue by Khushal-gupta22** [semrush/intergalactic#725]
I was building a table where I particularly want to decrease the width of Scroll Bar Slider of the DataTable , that goes by

<div class="___SSlider_1f8a5_gg_" data-ui-name="Bar.Slider" style="width: 462px; transform: translateX(0px);"></div> inside my DataTable component. How can I modify it's width and height in particular ?

**Comment by msereniti** [comment]
Hi, currently it's not possible with DataTable because ScrollArea component (the one responsible for scroll bar sliders) is not exposed from DataTable. Could you share why you might want to change size of the bar? (me personally can't even imagine a case)

**Comment by Khushal-gupta22** [comment]
> Hi, currently it's not possible with DataTable because ScrollArea component (the one responsible for scroll bar sliders) is not exposed from DataTable. Could you share why you might want to change size of the bar? (me personally can't even imagine a case)

I was making some data visualizations inside a particular column so the scroll bar overlapped with the graphical depiction of my data and it wasn't giving a good UI look according to my theme. 

I resolved the issue by picking up it's class and overwrote it in my global CSS file , issue is solved now ! . 
Great library btw !

**Comment by msereniti** [comment]
> I resolved the issue by picking up it's class and overwrote it in my global CSS file , issue is solved now ! .

Basically it's not a best choice because, if you would like to update library (lot of improvements come time-to-time) you will need to be careful – as you can see classnames contain hashes (e.g. `yn5k1` in `___SSlider_yn5k1_gg_`) that might change (without any special changelog note) from update to update.

But I would like not to expose scrollbars apis from datatable for now if global css is now working for you.
