### ISSUE TITLE
@semcore/flex-box tag property typing

### ISSUE THREAD

**Issue by mkarachev** [semrush/intergalactic#740]
**Describe the bug**
After the last major update, I've met an issue related to typings of @semcore/flex-box component. Tag property seems working wrong, forwarding property "tag" from Box interface to the Box component is marked as invalid. 

**Code example**
[Example](https://codesandbox.io/s/amazing-ully-v6fr5z?file=/src/App.tsx)

**To Reproduce**
All steps listed in an example.

**Expected behavior**
Box component will recognise "tag" property from it's interface as a valid value

**Comment by msereniti** [comment]
Hi, `tag` property is a special property that is used for correct component props merging and component typings polymorphism. It's not mentioned in `BoxProps` as all DOM props – it's all is coming from the type of `Box` component.

If you want to declare a wrapper over a `Box` component, you should something like that:
```tsx
import React from 'react';
import { Box, BoxProps } from '@semcore/ui/flex-box';

const BoxWrapper = ((props: { tag: unknown } & BoxProps & React.HTMLAttributes<HTMLDivElement>) => {
  ...
}) as typeof Box; 
```

**Comment by mkarachev** [comment]
I was pretty sure, that tag property is used to rewrite component's root node render.
Your example isn't working. Also I provided an example below, can you suggest any solution to make it work?
Here is [codesandbox](https://codesandbox.io/s/angry-meitner-l6kxh9?file=/src/App.tsx)

**Comment by msereniti** [comment]
Fixed code of the codesandbox:

```tsx
import React from "react";
import { Box, BoxProps } from "@semcore/ui/flex-box";

const BoxWrapper = ((props: any) => {
  return <Box {...props} />;
}) as typeof Box;

type MyComponentProps = BoxProps & {
  items: string[];
  tag?: "ol";
  p?: number;
};

const List: React.FC<MyComponentProps> = ({ items, ...other }) => {
  return (
    <Box tag="ul" {...other}>
      {items.map((item, index) => (
        <li key={index}>{item}</li>
      ))}
    </Box>
  );
};

const items = ["first", "second", "third"];

export default () => (
  <React.Fragment>
    <List items={items} p={0} />
    <List items={items} tag="ol" />
  </React.Fragment>
);
```

1. If you just passing props to the wrapped component – you don't need to specify prop types inside of wrapper because outside of wrapper it will be typed due to use of the `as` operator.
2. If you are going to pass limited set of props to the wrapped components – explicitly specify them with as narrow type as possible (in most cases narrow type will apply well).
3. If you want to declare polymorphic component with types that work similar to the libraries component but with your own props, you can declare them with `Intergalactic.Component` type like the following:

```tsx
import {  Intergalactic } from '@semcore/core';

type MySuperButtonProps = {
  a: number;
  b: string;
  c: boolean;
};
const MySuperButton = ((props: MySuperButtonProps & Intergalactic.DomProps<'button'>) => {
  return ...
}) as unknown as Intergalactic.Component<'button', MySuperButtonProps> 
```

Outside it will be strongly typed and will extend types when `tag` prop is provided. Inside – specify `tag` prop on props by yourself and it's better to specify them as `unkown` because you will not really know what is going to be passed. 

If `tag` prop is just passed to the one of normal component – feel free to type it as `any` because in that case you will just pass internal prop that is typed outside and you don't really need to care about it.

**Comment by mkarachev** [comment]
I think it would be easier to use, if you simply will add `Intergalactic.InternalTypings.ComponentTag` type to Box interface. 
Is it possible?

**Comment by msereniti** [comment]
> I think it would be easier to use, if you'll simply add Intergalactic.InternalTypings.ComponentTag type to Box interface.
Is it possible?

If we do so, it will be impossible to strictly type check polymorphic components (components with `tag` prop). 

I think that troubles you are facing are caused by wrong using polymorphic components. Basically you should not create a lot of them in your project but if you do – need to be careful and use that `Intergalctic.Component` generic.
