### ISSUE TITLE
Focus changing between several Selects 

### ISSUE THREAD

**Issue by Peoplecanfly1** [semrush/intergalactic#820]
Hello team, above 14+ version I have an issue with focus changing from one Select to another one.  
Algorithm: 
1. Click first select, choose item.   

Expected behaviour:  Next Select popper will appear.  

Look at example [here](https://codesandbox.io/s/objective-leftpad-mvnzv7) is version 13 and it works as I expect. 
If you update version on 14+ focuss will jump back to first Selector. 

Can you help me with managing it? Thanks.

**Comment by msereniti** [comment]
Why you are facing the issue:

Since the version `14.7.0` after selecting an option in dropdown, the Select component sets user focus back to the Select trigger. The most basic way you can hack it is to put `setCurrent(2);` into `setTimeout` with `1` delay + adding `animationsDisabled` on the Select (without `animationsDisabled` your timeout should finish after animation).

 What I recommend you to do:
 1. Set `ref`s on `Input.Value`, not on `Input`.
 2. Put `setCurrent(n);` into `setTimeout(..., 1);` to handle user focus switch after all async focus movements are done.
 3. Besides `setCurrent(n);` (in `setTimeout`) add `ref.currenct.focus()` to focus on corresponding input.
 
 Focussing on input is even more important than setting visible to true because it guarantees correct user focus flow.
