### ISSUE TITLE
Make TH cells with tooltips accessible from the keyboard

### ISSUE THREAD

**Issue by j-mnizhek** [semrush/intergalactic#890]
**Is your feature request related to a problem? Please describe.**
Can we make our TH cells accessible from the keyboard when they have tooltip?

**Describe the solution you'd like**
Let's look at [one of our examples from the website](https://developer.semrush.com/intergalactic/table-group/data-table/data-table-code#customizing-header). Now you can only access the cell with select:

<img width="748" alt="image" src="https://github.com/semrush/intergalactic/assets/77798437/632eee0b-555b-4d8a-8034-d35d0e2bd7fd">

Other TH cells aren't accessible. Other cells have tooltips that should be read when user access table with keyboard.

1. Can we include TH cells with tooltips to the Tab sequence? (I've seen that it worked before the website migration, maybe something broke).
2. Can we show Tooltip when user access the TH cell with Tooltip?

**Comment by ilyabrower** [comment]
It is not a problem in a `Table`, but in a `Tooltip`. 
Let's see an example:
```
<Tooltip title='Hello, stranger'>
    Trigger
</Tooltip>
```
By default, we don't add `tabIndex` to the `div` with `Trigger`. That's why, I think, all our examples looks like:
```
<Tooltip title='Hello, stranger'>
    <Link>Trigger</Link>
</Tooltip>
```
Because, `Link` has attribute `tabIndex=0`.

So, my suggestion is one of:
- add `tabIndex` it in every Tooltips by default (and disable it if we have something like `Link` in children)
- wrap children with some element with `tabIndex` every time

**Comment by j-mnizhek** [comment]
@ilyabrower Thank you! ❤️ Sorry, I've missed your comment somehow.
I've just checked adding tabIndex to tooltips inside TH cells in sandbox, and it works good.
I guess, it's worth while to add tabIndex in our table examples.

**Comment by j-mnizhek** [comment]
Fixed in this https://github.com/semrush/intergalactic/pull/1637
